def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('auth', '/auth')
    config.add_route('logout', '/logout')
    config.add_route('profile', '/profile')
    config.add_route('profile/delete', '/profile/delete')
    config.add_route('analytics', '/analytics')
    config.add_route('about', '/about')
    config.add_route('search', '/search')
    config.add_route('search/email', '/search/email')
    config.add_route('search/results', '/search/results')
    config.add_route('jobs', '/jobs')
    config.add_route('keywords', '/keywords')
    config.add_route('keywords/delete', '/keywords/delete')
